[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache/ms-playwright"

[phases.setup]
nixPkgs = ["playwright-driver.browsers"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[start]
cmd = "python main.py"
