[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache/ms-playwright"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "playwright-driver.browsers"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "python3 -m playwright install chromium"
]

[start]
cmd = "python3 main.py"
